apiVersion: apps/v1
kind: Deployment
metadata: 
   name: firstd
   labels:
     name: firstd
spec:
  replicas: 10
  minReadySeconds: 10
  strategy:
    rollingUpdate: 
      maxSurge: 0
      maxUnavailable: 2
    type: RollingUpdate
  selector:
     matchLabels: 
       app: myapp1
  template:
    metadata:
      name: dpop
      labels: 
        app: myapp1 
    spec:
       containers:
         - name: container1
           image: coolgourav147/nginx-custom:v2

