apiVersion: v1
kind: ReplicationController
metadata: 
   name: firstrc
   labels:
      name: firstrc
spec:
   replicas: 5
   template:
     metadata:
        name: nginx-pod   #podname&labels
        labels: 
          name: nginx
     spec:
       containers:
         - name: c1
           image: coolgourav147/nginx-custom
