apiVersion: v1
kind: Service
metadata:
   name: lbservice
   labels: 
     name: lbservice
spec:
   type: LoadBalancer
   selector:
     name: nginx 
   ports:
     - targetPort: 80
       port: 80
       protocol: TCP
