name: React Frontend CI

on:
  push:
    branches:
      - MAIN

jobs:
  build:
    runs-on: self-hosted
    tags:
      - k8s

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
